# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Develop Build

on:
  push:
    branches: [ develop ]
    paths-ignore:
    - 'pom.xml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"                
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean deploy -Dserver.username=$GITHUB_ACTOR -Dserver.token=${{ secrets.GITHUB_TOKEN }} -s settings.xml --file pom.xml
    - name: Build Docker Images
      run: |
        echo ${{ secrets.Dockerhub_Pwd }} | docker login registry.hub.docker.com --username ${{ secrets.Dockerhub_Login }} --password-stdin
        docker build -t project-info:latest --build-arg App_Username=${{ secrets.App_Username }} --build-arg App_Token=${{ secrets.App_Token }} .
        docker tag project-info:latest registry.hub.docker.com/tribui2106/project-info:latest
        docker push registry.hub.docker.com/tribui2106/project-info:latest
        