name: Release Event

on:
  release:
    types: [created,published,released]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"                    
    - name: Release
      run: |
        echo "Release event" 
