name: Variable tests on Github

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sets Variable
      run: |
        export BUILD_VERSION=1.2.2
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        env
    - name: Show Variable
      run: |
        echo "BUILD_VERSION='$BUILD_VERSION'"
  build_vars:
    runs-on: ubuntu-latest
    steps:
    - name: Sets Variable
      run: |
        echo "JAVA_HOME_LOCAL=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - name: Show Variable
      run: |
        echo "Java Home  = $JAVA_HOME_LOCAL"

