name: Variable tests on Github

env:
  JAVA_TEST_OPT: "Initial Workflow env Opt"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sets Variable
      run: |
        export BUILD_VERSION=1.2.2
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        env
    - name: Show Variable
      run: |
        echo "BUILD_VERSION='$BUILD_VERSION'"
        echo "JAVA_TEST_OPT=$JAVA_TEST_OPT"
    - name: Modify environment variable
      run: |
        export JAVA_TEST_OPT=""Modified JAVA_TEST_OPT"
        echo "modifed JAVA_TEST_OPT=$JAVA_TEST_OPT"
    - name: Show Variable after modification
      run: |
        echo "after modification steps JAVA_TEST_OPT=$JAVA_TEST_OPT"
            
  build_vars:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Sets Variable
      run: |
        echo "JAVA_HOME_LOCAL=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - name: Show Variable
      run: |
        echo "Java Home  = $JAVA_HOME_LOCAL"
        echo "BUILD_VERSION  = $BUILD_VERSION"
        echo "JAVA_TEST_OPT=$JAVA_TEST_OPT"
